spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lsge?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/migration
    schemas: lsge
    enabled: true
    user: root
    password: root
server:
  port: 18081
  servlet:
    session:
      timeout: 5m

app:
  security:
    non-auth-api: /api/health/*