spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lsge?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/migration
    schemas: lsge
    enabled: true
    user: root
    password:
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  redis:
    host: localhost
    password: 98rSV6XdF&t7x@4b
    port: 6379
server:
  port: 18081
  servlet:
    session:
      timeout: 5m

app:
  security:
    non-auth-api: /api/health/*